// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6sKf0ek9ScjdwldA1vq0RZpxJPaYg_cI',
    appId: '1:609040146801:web:873caa87ca1df33e5896d0',
    messagingSenderId: '609040146801',
    projectId: 'mitchinotif',
    authDomain: 'mitchinotif.firebaseapp.com',
    storageBucket: 'mitchinotif.firebasestorage.app',
    measurementId: 'G-ERNV12WJES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCReQkNvlqoQeIBQFoKl4Ye9fnTP2qa9_A',
    appId: '1:609040146801:android:9d49a96ec89af3f65896d0',
    messagingSenderId: '609040146801',
    projectId: 'mitchinotif',
    storageBucket: 'mitchinotif.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7AYltYfJThmoEJBoLn7SUN2-azYjhdc',
    appId: '1:609040146801:ios:695a1ee8ac5049935896d0',
    messagingSenderId: '609040146801',
    projectId: 'mitchinotif',
    storageBucket: 'mitchinotif.firebasestorage.app',
    iosBundleId: 'com.example.notif',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7AYltYfJThmoEJBoLn7SUN2-azYjhdc',
    appId: '1:609040146801:ios:695a1ee8ac5049935896d0',
    messagingSenderId: '609040146801',
    projectId: 'mitchinotif',
    storageBucket: 'mitchinotif.firebasestorage.app',
    iosBundleId: 'com.example.notif',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6sKf0ek9ScjdwldA1vq0RZpxJPaYg_cI',
    appId: '1:609040146801:web:d688f525a2f5f2d95896d0',
    messagingSenderId: '609040146801',
    projectId: 'mitchinotif',
    authDomain: 'mitchinotif.firebaseapp.com',
    storageBucket: 'mitchinotif.firebasestorage.app',
    measurementId: 'G-MQ2E5B7B1L',
  );
}
